import { ptBR } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { Toaster } from "./_components/ui/sonner";
import "./globals.css";

const siteUrl = "https://www.openmatch.io";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "OpenMatch: Encontre sua Primeira Contribuição Open Source",
    template: `%s | OpenMatch`,
  },
  description:
    "O OpenMatch conecta desenvolvedores iniciantes a issues e projetos de software livre no GitHub. Encontre a oportunidade perfeita e faça sua primeira contribuição para o mundo open source hoje mesmo!",
  keywords: [
    "open source",
    "código aberto",
    "primeira contribuição",
    "desenvolvedor iniciante",
    "GitHub",
    "issues para iniciantes",
    "projetos open source",
    "contribuir com software livre",
    "good first issue",
    "beginner friendly",
    "contribute to open source",
  ],

  authors: [{ name: "André Timm", url: "https://github.com/andretimm" }],
  creator: "André Timm",
  publisher: "André Timm",

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  openGraph: {
    title: "OpenMatch: Sua Porta de Entrada para o Open Source",
    description:
      "Encontre projetos e issues no GitHub selecionados para iniciantes e faça sua primeira contribuição de forma guiada e amigável.",
    url: siteUrl,
    siteName: "OpenMatch",
    images: [
      {
        url: `${siteUrl}/og-image.png`,
        width: 1200,
        height: 630,
        alt: "OpenMatch - Conectando Desenvolvedores a Projetos Open Source",
      },
    ],
    locale: "pt_BR",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "OpenMatch: Encontre sua Primeira Contribuição Open Source",
    description:
      'A ponte entre desenvolvedores iniciantes e o universo do código aberto. Encontre sua "good first issue" aqui!',
    creator: "timm_dev",
    images: [`${siteUrl}/og-image.png`],
  },
  // Links Canônicos e Alternativos
  // --------------------------------------------------
  alternates: {
    canonical: "/",
    languages: {
      "pt-BR": "/pt-BR",
    },
  },

  // Verificação de Sites (ex: Google Search Console)
  // --------------------------------------------------
  // verification: {
  //   google: "SUA_CHAVE_DE_VERIFICACAO_DO_GOOGLE",
  // },
};

// export const metadata: Metadata = {
//   title: {
//     default: "OpenMatch: Encontre sua Primeira Contribuição Open Source",
//     template: `%s | OpenMatch`,
//   },
//   description: "Generated by create next app",
//   applicationName: "Open Source Match",
//   keywords: [
//     "open source",
//     "github",
//     "contribution",
//     "projects",
//     "community",
//     "programming",
//     "development",
//     "software",
//     "technology",
//     "opensource",
//     "match",
//     "find projects",
//     "discover projects",
//     "programming languages",
//     "tech stack",
//     "collaboration",
//     "developer community",
//     "contributor",
//     "coding",
//     "software development",
//     "git",
//     "git repository",
//     "git projects",
//     "git contributions",
//     "git collaboration",
//     "git community",
//     "git open source",
//     "git match",
//   ],
//   authors: [
//     {
//       name: "Open Source Match Team",
//       url: "https://github.com/OpenSourceMatch",
//     },
//   ],
//   creator: "Open Source Match Team",
//   themeColor: "#000000",
//   colorScheme: "dark",
//   icons: {
//     icon: "/favicon.ico",
//     shortcut: "/favicon.ico",
//     apple: "/apple-touch-icon.png",
//   },
//   openGraph: {
//     title: "Open Source Match",
//     description: "Descubra projetos incríveis do GitHub de forma divertida.",
//     url: "https://opensourcematch.com",
//     siteName: "Open Source Match",
//     images: [
//       {
//         url: "https://opensourcematch.com/og-image.png",
//         width: 1200,
//         height: 630,
//         alt: "Open Source Match - Descubra projetos incríveis do GitHub de forma divertida.",
//       },
//     ],
//     locale: "pt-BR",
//     type: "website",
//   },
//   twitter: {
//     card: "summary_large_image",
//     title: "Open Source Match",
//     description: "Descubra projetos incríveis do GitHub de forma divertida.",
//     images: ["https://opensourcematch.com/og-image.png"],
//     creator: "@OpenSourceMatch",
//   },
//   robots: {
//     index: true,
//     follow: true,
//     nocache: false,
//     noimageindex: false,
//     noarchive: false,
//     nosnippet: false,
//   },
//   alternates: {
//     canonical: "https://opensourcematch.com",
//     languages: {
//       "pt-BR": "https://opensourcematch.com",
//       "en-US": "https://opensourcematch.com/en",
//     },
//   },
//   verification: {
//     google: "google-site-verification=your-google-verification-code",
//     yandex: "yandex-verification: your-yandex-verification-code",
//     me: "me-verification: your-me-verification-code",
//   },
//   manifest: "/manifest.json",
//   appleWebApp: {
//     capable: true,
//     title: "Open Source Match",
//     statusBarStyle: "black-translucent",
//     startupImage: [
//       "/apple-touch-icon.png",
//       "/apple-touch-icon-180x180.png",
//       "/apple-touch-icon-120x120.png",
//       "/apple-touch-icon-76x76.png",
//     ],
//   },
//   formatDetection: {
//     telephone: false,
//     address: false,
//     email: false,
//   },
//   viewport: "width=device-width, initial-scale=1",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
      localization={ptBR}
    >
      <html lang="pt-BR">
        <head>
          <meta name="apple-mobile-web-app-title" content="Open Match" />
        </head>
        <body>
          <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-black text-white">
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-purple-900/20 via-transparent to-transparent"></div>
            <div className="absolute top-1/4 left-1/4 w-48 h-48 md:w-96 md:h-96 bg-blue-500/10 rounded-full blur-3xl"></div>
            <div className="absolute bottom-1/4 right-1/4 w-48 h-48 md:w-96 md:h-96 bg-purple-500/10 rounded-full blur-3xl"></div>
            {children}
            <Analytics />
          </div>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
